---
- name: Installer Docker sur les Nodes
  hosts: master
  become: true

  tasks:
    - name: Copier le script d'installation
      copy:
        src: ./script.sh
        dest: /home/ubuntu/script.sh
        mode: '0755'

    - name: Exécuter le script
      command: /home/ubuntu/script.sh